# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install curl
RUN apt-get update && apt-get install -y curl

# Download CockroachDB root certificate
RUN curl --create-dirs -o $HOME/.postgresql/root.crt 'https://cockroachlabs.cloud/clusters/72fb5af8-4272-4987-ab3e-9f2fbb5cb767/cert'

# Copy the current directory contents into the container at /app
COPY ./app /app/app

COPY alembic /app/


COPY main.py /app/
COPY alembic.ini /app/

COPY __init__.py /app/



# Copy the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 8000

# Run main.py when the container launches
CMD ["python", "main.py"]
