version: "3.8"

services:
  fastapi_backend:
    container_name: my_fastapi_backend
    build: .
    env_file:
      - .env.prod
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    name: my-network
